source 'git@gitlab.avm.de:ENT-Apps-IOS/AVMPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'file:///Users/claus/Workspace/PrivateSpecs.git'

platform :ios, '10.0'
use_frameworks!

$static_framework = ['MixedErrorLog']

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
      def pod.host_requires_frameworks?
        false
      end
      puts "Overriding the build_as_static_framework? method for #{pod.name}"
      def pod.build_as_static_framework?
        true
      end
    end
  end
end


target 'MixedLog_Example' do
  pod 'MixedLog', :path => '../'
  pod 'MixedErrorLog', :path => '../../MixedErrorLog', :modular_headers => true

  target 'MixedLog_Tests' do
    inherit! :search_paths
  end
end

